#!/bin/zsh
battery=$(acpi -b | grep "Battery" | awk '{print $5;}' | cut -c 1-5)
if [ "$battery" = "until" ]; then
	echo "Full"
else if [ "$battery" = "" ]; then 
	echo "Full"
else
	echo $battery
fi
fi
